[package]
name = "actix-client-leak"
version = "0.1.0"
authors = ["sfisol <wolfmoon@o2.pl>"]
edition = "2018"

[dependencies]
actix-web = { version = "3.2.0", features = ["openssl"] }
openssl = "0.10"
procinfo = "0.4"
